export const INTELLIGENCE_SIGNALS = {
  conservative_majority_pct: {
    key: "conservative_majority_pct",
    label: "Conservative majority %",
    description: "Winning Conservative majority expressed as a share of votes or electorate baseline.",
    usedInModels: ["vulnerability", "reformThreat", "byElectionRisk"],
    dataSourceKey: "general_election_results",
    signalType: "electoral",
    historicalCoverage: "high",
    currentCoverage: "high",
    auditStatus: "robust",
    notes: "Foundational seat exposure signal with broad historical comparability.",
  },
  conservative_vote_share_change: {
    key: "conservative_vote_share_change",
    label: "Conservative vote share change",
    description: "Change in Conservative vote share between election cycles.",
    usedInModels: ["vulnerability", "scenarioSimulator"],
    dataSourceKey: "general_election_results",
    signalType: "electoral",
    historicalCoverage: "high",
    currentCoverage: "high",
    auditStatus: "robust",
    notes: "Useful for ranking defensive deterioration when measured cycle to cycle.",
  },
  challenger_gap: {
    key: "challenger_gap",
    label: "Challenger gap",
    description: "Distance between the incumbent and strongest challenger in the seat.",
    usedInModels: ["vulnerability", "byElectionRisk"],
    dataSourceKey: "general_election_results",
    signalType: "electoral",
    historicalCoverage: "high",
    currentCoverage: "high",
    auditStatus: "robust",
    notes: "Reliable for relative seat competitiveness and ranking.",
  },
  reform_vote_share: {
    key: "reform_vote_share",
    label: "Reform vote share",
    description: "Reform UK vote share in the latest available Westminster result.",
    usedInModels: ["vulnerability", "reformThreat", "scenarioSimulator"],
    dataSourceKey: "general_election_results",
    signalType: "electoral",
    historicalCoverage: "medium",
    currentCoverage: "high",
    auditStatus: "robust",
    notes: "Current-cycle signal is strong; longer-run comparability is weaker because the party system changed.",
  },
  con_reform_swing: {
    key: "con_reform_swing",
    label: "Conservative to Reform swing",
    description: "Measured or inferred swing from Conservative to Reform between cycles.",
    usedInModels: ["reformThreat"],
    dataSourceKey: "notional_results",
    signalType: "derived",
    historicalCoverage: "medium",
    currentCoverage: "high",
    auditStatus: "noisy",
    notes: "Operationally useful but sensitive to notional baselines and party-system shifts.",
  },
  local_reform_presence: {
    key: "local_reform_presence",
    label: "Local Reform presence",
    description: "Evidence of Reform activity or local electoral presence below Westminster level.",
    usedInModels: ["reformThreat"],
    dataSourceKey: "local_government_results",
    signalType: "local_government",
    historicalCoverage: "low",
    currentCoverage: "medium",
    auditStatus: "noisy",
    notes: "Good directional clue where available, but patchy nationally and not evenly historicised.",
  },
  turnout_volatility: {
    key: "turnout_volatility",
    label: "Turnout volatility",
    description: "How much turnout has varied between recent cycles in the seat.",
    usedInModels: ["scenarioSimulator", "byElectionRisk"],
    dataSourceKey: "general_election_results",
    signalType: "derived",
    historicalCoverage: "medium",
    currentCoverage: "medium",
    auditStatus: "noisy",
    notes: "Useful for scenario framing, but not reliable enough as a standalone predictive signal.",
  },
  demographic_headwinds: {
    key: "demographic_headwinds",
    label: "Demographic headwinds",
    description: "Composite of demographic attributes associated with political pressure in the seat.",
    usedInModels: ["vulnerability", "reformThreat"],
    dataSourceKey: "constituency_demographics",
    signalType: "demographic",
    historicalCoverage: "medium",
    currentCoverage: "high",
    auditStatus: "noisy",
    notes: "Best used as a supporting structural context signal, not a decisive predictor.",
  },
  alert_pressure: {
    key: "alert_pressure",
    label: "Alert pressure",
    description: "Intensity of active political alerts associated with the seat.",
    usedInModels: ["byElectionRisk"],
    dataSourceKey: "political_alerts",
    signalType: "alert",
    historicalCoverage: "low",
    currentCoverage: "medium",
    auditStatus: "insufficient_data",
    notes: "Current monitoring value is clear, but historical backtesting coverage is limited.",
  },
  mp_instability: {
    key: "mp_instability",
    label: "MP instability",
    description: "Signals of resignation, suspension, defection, scandal, or member-level instability.",
    usedInModels: ["byElectionRisk"],
    dataSourceKey: "mp_events",
    signalType: "mp",
    historicalCoverage: "low",
    currentCoverage: "medium",
    auditStatus: "insufficient_data",
    notes: "Useful current-intelligence indicator, but event history is incomplete and inconsistently structured.",
  },
  local_government_instability: {
    key: "local_government_instability",
    label: "Local government instability",
    description: "Instability signal derived from local authority changes and council-level shifts.",
    usedInModels: ["byElectionRisk", "reformThreat"],
    dataSourceKey: "local_government_results",
    signalType: "local_government",
    historicalCoverage: "low",
    currentCoverage: "medium",
    auditStatus: "noisy",
    notes: "Potentially useful, but cross-authority coverage is incomplete and timing is uneven.",
  },
  anti_incumbent_pressure: {
    key: "anti_incumbent_pressure",
    label: "Anti-incumbent pressure",
    description: "Broad deterioration or anti-government pressure acting against the incumbent side.",
    usedInModels: ["vulnerability", "byElectionRisk"],
    dataSourceKey: "polling_and_trends",
    signalType: "derived",
    historicalCoverage: "medium",
    currentCoverage: "medium",
    auditStatus: "noisy",
    notes: "Directionally useful at a high level but coarse at individual-seat level.",
  },
  fragmentation_pressure: {
    key: "fragmentation_pressure",
    label: "Fragmentation pressure",
    description: "Pressure created by vote splitting within or across political blocs.",
    usedInModels: ["reformThreat", "byElectionRisk"],
    dataSourceKey: "general_election_results",
    signalType: "derived",
    historicalCoverage: "medium",
    currentCoverage: "medium",
    auditStatus: "noisy",
    notes: "Important conceptually, but exact quantification remains model-dependent.",
  },
};

export function getIntelligenceSignal(signalKey) {
  return INTELLIGENCE_SIGNALS[signalKey] ?? null;
}

export function listSignalsForModel(modelKey) {
  return Object.values(INTELLIGENCE_SIGNALS).filter((signal) => signal.usedInModels.includes(modelKey));
}
