#!/bin/sh
set -e

AWS_REGION="${AWS_REGION:-eu-west-2}"
STACK_NAME="${STACK_NAME:-ps-enquiry-api-prod}"
ALLOWED_ORIGINS="${ALLOWED_ORIGINS:-${ALLOWED_ORIGIN:-}}"
FROM_EMAIL="${FROM_EMAIL:-}"
TO_EMAIL="${TO_EMAIL:-}"
OPS_EMAIL_TO="${OPS_EMAIL_TO:-}"
FRONTEND_BASE_URL="${FRONTEND_BASE_URL:-}"
XERO_CLIENT_ID="${XERO_CLIENT_ID:-}"
XERO_CLIENT_SECRET="${XERO_CLIENT_SECRET:-}"
XERO_REDIRECT_URI="${XERO_REDIRECT_URI:-}"
XERO_TOKEN_PARAM_NAME="${XERO_TOKEN_PARAM_NAME:-}"
XERO_SALES_ACCOUNT_CODE="${XERO_SALES_ACCOUNT_CODE:-}"
XERO_TAX_TYPE="${XERO_TAX_TYPE:-}"
XERO_INVOICE_STATUS="${XERO_INVOICE_STATUS:-}"
XERO_STATE_SECRET="${XERO_STATE_SECRET:-}"
XERO_DUE_DAYS="${XERO_DUE_DAYS:-}"
XERO_EMAIL_INVOICE="${XERO_EMAIL_INVOICE:-}"
XERO_TEST_INVOICE_ENABLED="${XERO_TEST_INVOICE_ENABLED:-}"
QUOTE_TTL_ENABLED="${QUOTE_TTL_ENABLED:-}"
QUOTE_TTL_DAYS="${QUOTE_TTL_DAYS:-}"
COGNITO_ISSUER="${COGNITO_ISSUER:-}"
COGNITO_AUDIENCE="${COGNITO_AUDIENCE:-}"
ALARM_TOPIC_ARN="${ALARM_TOPIC_ARN:-}"
THROTTLE_RPS="${THROTTLE_RPS:-}"
THROTTLE_BURST="${THROTTLE_BURST:-}"
WAF_ENABLED="${WAF_ENABLED:-}"
WAF_RATE_LIMIT="${WAF_RATE_LIMIT:-}"
WAF_MANAGED_RULES_ENABLED="${WAF_MANAGED_RULES_ENABLED:-}"
WAF_LOGGING_ENABLED="${WAF_LOGGING_ENABLED:-}"
WAF_LOG_RETENTION_DAYS="${WAF_LOG_RETENTION_DAYS:-}"

if [ -z "$ALLOWED_ORIGINS" ] || [ -z "$FROM_EMAIL" ] || [ -z "$TO_EMAIL" ]; then
  echo "Missing required env vars."
  echo "Set ALLOWED_ORIGINS (or ALLOWED_ORIGIN), FROM_EMAIL, and TO_EMAIL before running."
  exit 1
fi

cd infra/enquiry-api

sam build
PARAM_OVERRIDES="AllowedOrigins=${ALLOWED_ORIGINS} FromEmail=${FROM_EMAIL} ToEmail=${TO_EMAIL}"
if [ -n "$OPS_EMAIL_TO" ]; then
  PARAM_OVERRIDES="$PARAM_OVERRIDES OpsEmailTo=${OPS_EMAIL_TO}"
fi
if [ -n "$FRONTEND_BASE_URL" ]; then
  PARAM_OVERRIDES="$PARAM_OVERRIDES FrontendBaseUrl=${FRONTEND_BASE_URL}"
fi
if [ -n "$XERO_CLIENT_ID" ]; then
  PARAM_OVERRIDES="$PARAM_OVERRIDES XeroClientId=${XERO_CLIENT_ID}"
fi
if [ -n "$XERO_CLIENT_SECRET" ]; then
  PARAM_OVERRIDES="$PARAM_OVERRIDES XeroClientSecret=${XERO_CLIENT_SECRET}"
fi
if [ -n "$XERO_REDIRECT_URI" ]; then
  PARAM_OVERRIDES="$PARAM_OVERRIDES XeroRedirectUri=${XERO_REDIRECT_URI}"
fi
if [ -n "$XERO_TOKEN_PARAM_NAME" ]; then
  PARAM_OVERRIDES="$PARAM_OVERRIDES XeroTokenParamName=${XERO_TOKEN_PARAM_NAME}"
fi
if [ -n "$XERO_SALES_ACCOUNT_CODE" ]; then
  PARAM_OVERRIDES="$PARAM_OVERRIDES XeroSalesAccountCode=${XERO_SALES_ACCOUNT_CODE}"
fi
if [ -n "$XERO_TAX_TYPE" ]; then
  PARAM_OVERRIDES="$PARAM_OVERRIDES XeroTaxType=${XERO_TAX_TYPE}"
fi
if [ -n "$XERO_INVOICE_STATUS" ]; then
  PARAM_OVERRIDES="$PARAM_OVERRIDES XeroInvoiceStatus=${XERO_INVOICE_STATUS}"
fi
if [ -n "$XERO_STATE_SECRET" ]; then
  PARAM_OVERRIDES="$PARAM_OVERRIDES XeroStateSecret=${XERO_STATE_SECRET}"
fi
if [ -n "$XERO_DUE_DAYS" ]; then
  PARAM_OVERRIDES="$PARAM_OVERRIDES XeroDueDays=${XERO_DUE_DAYS}"
fi
if [ -n "$XERO_EMAIL_INVOICE" ]; then
  PARAM_OVERRIDES="$PARAM_OVERRIDES XeroEmailInvoice=${XERO_EMAIL_INVOICE}"
fi
if [ -n "$XERO_TEST_INVOICE_ENABLED" ]; then
  PARAM_OVERRIDES="$PARAM_OVERRIDES XeroTestInvoiceEnabled=${XERO_TEST_INVOICE_ENABLED}"
fi
if [ -n "$QUOTE_TTL_ENABLED" ]; then
  PARAM_OVERRIDES="$PARAM_OVERRIDES QuoteTtlEnabled=${QUOTE_TTL_ENABLED}"
fi
if [ -n "$QUOTE_TTL_DAYS" ]; then
  PARAM_OVERRIDES="$PARAM_OVERRIDES QuoteTtlDays=${QUOTE_TTL_DAYS}"
fi
if [ -n "$COGNITO_ISSUER" ]; then
  PARAM_OVERRIDES="$PARAM_OVERRIDES CognitoIssuer=${COGNITO_ISSUER}"
fi
if [ -n "$COGNITO_AUDIENCE" ]; then
  PARAM_OVERRIDES="$PARAM_OVERRIDES CognitoAudience=${COGNITO_AUDIENCE}"
fi
if [ -n "$ALARM_TOPIC_ARN" ]; then
  PARAM_OVERRIDES="$PARAM_OVERRIDES AlarmTopicArn=${ALARM_TOPIC_ARN}"
fi
if [ -n "$THROTTLE_RPS" ]; then
  PARAM_OVERRIDES="$PARAM_OVERRIDES ThrottlingRateLimit=${THROTTLE_RPS}"
fi
if [ -n "$THROTTLE_BURST" ]; then
  PARAM_OVERRIDES="$PARAM_OVERRIDES ThrottlingBurstLimit=${THROTTLE_BURST}"
fi
if [ -n "$WAF_ENABLED" ]; then
  PARAM_OVERRIDES="$PARAM_OVERRIDES WafEnabled=${WAF_ENABLED}"
fi
if [ -n "$WAF_RATE_LIMIT" ]; then
  PARAM_OVERRIDES="$PARAM_OVERRIDES WafRateLimit=${WAF_RATE_LIMIT}"
fi
if [ -n "$WAF_MANAGED_RULES_ENABLED" ]; then
  PARAM_OVERRIDES="$PARAM_OVERRIDES WafManagedRulesEnabled=${WAF_MANAGED_RULES_ENABLED}"
fi
if [ -n "$WAF_LOGGING_ENABLED" ]; then
  PARAM_OVERRIDES="$PARAM_OVERRIDES WafLoggingEnabled=${WAF_LOGGING_ENABLED}"
fi
if [ -n "$WAF_LOG_RETENTION_DAYS" ]; then
  PARAM_OVERRIDES="$PARAM_OVERRIDES WafLogRetentionDays=${WAF_LOG_RETENTION_DAYS}"
fi

sam deploy --resolve-s3 \
  --stack-name "$STACK_NAME" \
  --capabilities CAPABILITY_IAM \
  --parameter-overrides $PARAM_OVERRIDES \
  --region "$AWS_REGION"

echo ""
echo "CloudFormation outputs:"
aws cloudformation describe-stacks \
  --stack-name "$STACK_NAME" \
  --query "Stacks[0].Outputs" \
  --region "$AWS_REGION"
